require_relative 'test_parser'
require_relative 'test_strings'
require_relative 'test_arrays'
require_relative 'test_hashes'
require_relative 'test_parens'
require_relative 'test_definitions'
require_relative 'test_control_flow'
require_relative 'test_heredocs'
